added population AIF functions
OSIPI/DCE-DSC-MRI_CodeCollection pull request #35
Opened 2021-04-22 13:31 UTC by petravanhoudt

Can you check if I followed the guidelines in the right way?

2021-04-22 14:09 UTC, mjt320 requested changes
Think this looks okay. If we're being strict the folder should be name_institute_country.
The subfolder naming is up to the contributor.
Thanks for the code :)

2021-04-23 08:41 UTC, petravanhoudt commented
I modified the dir name (with an underscore added however, otherwise institute and country cannot be distinguished). Should I create a new pull request?

2021-04-26 02:05 UTC, schudds commented
> I modified the dir name (with an underscore added however, otherwise institute and country cannot be distinguished). Should I create a new pull request?

@petravanhoudt : This looks good ! The underscore is fine to differentiate between Institute and country. Ready to be merged! :)

2021-04-26 02:06 UTC, schudds approved these changes

2021-05-06 07:52 UTC, merged